services:
  server:
    image: betterde/focusly:latest
    ports:
      - "0.0.0.0:443:443/tcp"
    networks:
      - focusly
    hostname: server
    environment:
      - FOCUSLY_ENV=production
      - FOCUSLY_HTTP_LISTEN=0.0.0.0:80
      - FOCUSLY_LOGGING_LEVEL=INFO
      # SurrealDB Configuration
      - FOCUSLY_DATABASE_URL=wss://surrealdb.database.local/rpc
      - FOCUSLY_DATABASE_DATABASE=focusly
      - FOCUSLY_DATABASE_USERNAME=surrealdb
      - FOCUSLY_DATABASE_PASSWORD=
      - FOCUSLY_DATABASE_NAMESPACE=betterde
    container_name: server
  surrealdb:
    user: "1000"
    image: surrealdb/surrealdb:latest
    restart: no
    volumes:
      - surrealdb-data:/surrealdb-data
    command: [ "start" ]
    hostname: surrealdb
    networks:
      - focusly
    environment:
      - SURREAL_BIND=0.0.0.0:8000
      - SURREAL_USER=surrealdb
      - SURREAL_PASS=
      - SURREAL_PATH=file:///surrealdb-data/surreal.db
      - SURREAL_CAPS_ALLOW_ALL=true
    container_name: surrealdb

volumes:
  surrealdb-data:
    name: surrealdb-data

networks:
  focusly:
    name: focusly