services:
  server:
    image: betterde/focusly:latest
    ports:
      - 0.0.0.0:443:443
    networks:
      - traefik
    hostname: server
    environment:
      - FOCUSLY_ENV=production
      - FOCUSLY_HTTP_LISTEN=0.0.0.0:80
      - FOCUSLY_HTTP_TLSKEY=/certs/domain.tld.key
      - FOCUSLY_HTTP_TLSCERT=/certs/domain.tld.crt
      - FOCUSLY_LOGGING_LEVEL=INFO
    container_name: server
  surrealdb:
    user: "1000"
    image: surrealdb/surrealdb:latest
    restart: no
    volumes:
      - surrealdb-data:/surrealdb-data
    command: [ "start" ]
    hostname: surrealdb
    networks:
      - traefik
    environment:
      - SURREAL_BIND=0.0.0.0:8000
      - SURREAL_USER=surrealdb
      - SURREAL_PASS=p9moC6XYruscCQfdHMHXfm7HQAaNZ8Am
      - SURREAL_PATH=file:///surrealdb-data/surreal.db
      - SURREAL_CAPS_ALLOW_ALL=true
    container_name: surrealdb

  volumes:
    surrealdb-data:
      name: surrealdb-data

networks:
  traefik:
    external: true